<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Description>Khefest is a modular C# 2D/3D graphics and game engine engineered for high performance on Windows with pure native abstractions.</Description>
    <PackageId>Khefest</PackageId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Khefest.Core\Khefest.Core.csproj" />
    <ProjectReference Include="..\Khefest.Windowing\Khefest.Windowing.csproj" />
    <ProjectReference Include="..\Khefest.Input\Khefest.Input.csproj" />
    <ProjectReference Include="..\Khefest.Graphics.LowLevel\Khefest.Graphics.LowLevel.csproj" />
    <ProjectReference Include="..\Khefest.Graphics\Khefest.Graphics.csproj" />
    <ProjectReference Include="..\Khefest.UI\Khefest.UI.csproj" />
    <ProjectReference Include="..\Khefest.Windows\Khefest.Windows.csproj" />
  </ItemGroup>

</Project>
