using Khefest.Input;

namespace Khefest.Windows.Native;

internal static class Win32KeyMapper
{
    public static Key MapVirtualKey(nuint wParam)
    {
        return wParam switch
        {
            0x41 => Key.A,
            0x42 => Key.B,
            0x43 => Key.C,
            0x44 => Key.D,
            0x45 => Key.E,
            0x46 => Key.F,
            0x47 => Key.G,
            0x48 => Key.H,
            0x49 => Key.I,
            0x4A => Key.J,
            0x4B => Key.K,
            0x4C => Key.L,
            0x4D => Key.M,
            0x4E => Key.N,
            0x4F => Key.O,
            0x50 => Key.P,
            0x51 => Key.Q,
            0x52 => Key.R,
            0x53 => Key.S,
            0x54 => Key.T,
            0x55 => Key.U,
            0x56 => Key.V,
            0x57 => Key.W,
            0x58 => Key.X,
            0x59 => Key.Y,
            0x5A => Key.Z,

            0x30 => Key.D0,
            0x31 => Key.D1,
            0x32 => Key.D2,
            0x33 => Key.D3,
            0x34 => Key.D4,
            0x35 => Key.D5,
            0x36 => Key.D6,
            0x37 => Key.D7,
            0x38 => Key.D8,
            0x39 => Key.D9,

            0x60 => Key.NumPad0,
            0x61 => Key.NumPad1,
            0x62 => Key.NumPad2,
            0x63 => Key.NumPad3,
            0x64 => Key.NumPad4,
            0x65 => Key.NumPad5,
            0x66 => Key.NumPad6,
            0x67 => Key.NumPad7,
            0x68 => Key.NumPad8,
            0x69 => Key.NumPad9,
            0x6A => Key.Multiply,
            0x6B => Key.Add,
            0x6D => Key.Subtract,
            0x6E => Key.Decimal,
            0x6F => Key.Divide,

            0x70 => Key.F1,
            0x71 => Key.F2,
            0x72 => Key.F3,
            0x73 => Key.F4,
            0x74 => Key.F5,
            0x75 => Key.F6,
            0x76 => Key.F7,
            0x77 => Key.F8,
            0x78 => Key.F9,
            0x79 => Key.F10,
            0x7A => Key.F11,
            0x7B => Key.F12,

            0x1B => Key.Escape,
            0x0D => Key.Enter,
            0x20 => Key.Space,
            0x09 => Key.Tab,
            0x08 => Key.Backspace,
            0x2D => Key.Insert,
            0x2E => Key.Delete,
            0x24 => Key.Home,
            0x23 => Key.End,
            0x21 => Key.PageUp,
            0x22 => Key.PageDown,

            0x26 => Key.Up,
            0x28 => Key.Down,
            0x25 => Key.Left,
            0x27 => Key.Right,

            0x10 => Key.LeftShift,
            0xA0 => Key.LeftShift,
            0xA1 => Key.RightShift,
            0x11 => Key.LeftControl,
            0xA2 => Key.LeftControl,
            0xA3 => Key.RightControl,
            0x12 => Key.LeftAlt,
            0xA4 => Key.LeftAlt,
            0xA5 => Key.RightAlt,
            0x5B => Key.LeftSuper,
            0x5C => Key.RightSuper,

            0x14 => Key.CapsLock,
            0x91 => Key.ScrollLock,
            0x90 => Key.NumLock,
            0x2C => Key.PrintScreen,
            0x13 => Key.Pause,

            0xBA => Key.Semicolon,
            0xBB => Key.Equals,
            0xBC => Key.Comma,
            0xBD => Key.Minus,
            0xBE => Key.Period,
            0xBF => Key.Slash,
            0xDC => Key.Backslash,
            0xDB => Key.LeftBracket,
            0xDD => Key.RightBracket,
            0xDE => Key.Apostrophe,
            0xC0 => Key.Grave,

            _ => Key.None
        };
    }
}
